### ISSUE TITLE
There is a problem with the analysis packet

### ISSUE THREAD

**Issue by qq1176914912** [odedshimon/BruteShark#106]
If there is a problem with this data packet, please take a look at it.
[test.zip](https://github.com/odedshimon/BruteShark/files/7112654/test.zip)

**Comment by odedshimon** [comment]
Hi @qq1176914912,
That's true there is a problem with the processing of this file.
I have figured that the reason is a library named Haukcode.PcapngUtils which is not needed anymore since SharpPcap added PCAP-NG support. 
You can follow the fix at this branch: [remove-haukcode-pcapng-nuget](https://github.com/odedshimon/BruteShark/tree/remove-haukcode-pcapng-nuget)

**Comment by odedshimon** [comment]
The file is currently being analyzed without any exceptions: 
![image](https://user-images.githubusercontent.com/18364847/132539164-79bbdda5-8325-433f-8aa6-f8f80f21cff3.png)
The above fix will take place at the next release.
Thank you for letting me know. 
Oded.
