### ISSUE TITLE
Support MacOS?

### ISSUE THREAD

**Issue by evandrix** [odedshimon/BruteShark#33]

**Comment by odedshimon** [comment]
Hi @evandrix 
Technically, .Net Core supports MacOS, so since BruteShark is fully implemented using .Net Core, it possible to run it on MacOS.
Yet, I didn't compiled or checked on MacOS due to a lack of time.
Feel free to clone this project and compile a MacOS version. 
In case you do that, you can update me with the required changes and I will update the project accordingly.

**Comment by nuschpl** [comment]
Hello @evandrix any progress on this ? I can contribute also but don't want to repeat the research if any job was already done

**Comment by evandrix** [comment]
i haven't had time to work on this since then, but i did verify that only `Brute Shark CLI` builds on MacOS, as expected, so a valuable contribution is to make the GUI + others work on MacOS. thanks

**Comment by odedshimon** [comment]
@evandrix @nuschpl 

@aviadtamir is currently working on adjusting the CI of this project (github actions) to be tested on multiple operating systems, including MacOS.
Relevant Branch: https://github.com/odedshimon/BruteShark/tree/upgrade-ci-multi-platform-build-and-test

**Comment by aviadtamir** [comment]
The Cli is running on MacOs, of course that dot net needs to be installed on the machine
