### ISSUE TITLE
Failure when export-hashes directory is not present

### ISSUE THREAD

**Issue by nuschpl** [odedshimon/BruteShark#52]
The app fails when export-hashes CLI option is called and no export-hashes directory is present in binary directory. After spending few hours on processing pcaps this may be quite frustrating - app should create the directory or at least ask the user. Probably writing to OS default temp directory and then moving to  per OS default location like current directory or $HOME/BruteShark/${date}/export-hashes-would be an option as in any permission problem case th user has then a way to recover the hashes

**Comment by odedshimon** [comment]
@nuschpl 

You are right, due to a lack of time unfortunately the user-interface is currently does not provide the required appropriate input checks and does not using local files to store parsed data.

**In the near future we plan to make significant refactor that will also allow BruteSharkCli to run as a single command line with all the options that the tool provides and the proper input checks.

Feel free to suggest a design or implementing a solution for this feature.**

**Comment by odedshimon** [comment]
Since version 1.1.5 proper cli user interface with all the needed capabilities has been implemented.
It includes proper input checks, help menu, and more. It can also automatically export the extracted results to a given directory.
I would love to get feedbacks.
